# because github actions are shit, we need to combine every workflow in one file in order to be able to have jobs depend correctly on other jobs

name: CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  SHOULD_PUBLISH_IMAGE: ${{ github.ref == 'refs/heads/main' }}

jobs:
  package_dist:
    name: Build and Package
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: python -m pip install --upgrade pip build
      - name: Build
        run: python -m build --sdist -o dist
      - name: Rename package to remove version number
        run: mv dist/openpectus_database_administration-*.tar.gz dist/openpectus_database_administration.tar.gz
      - name: Archive source distribution
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: |
            dist
            Dockerfile

  publish_docker_image:
    name: Publish Docker image
    needs: [ package_dist ]
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Download source distribution artifact
        if: env.SHOULD_PUBLISH_IMAGE == 'true'
        uses: actions/download-artifact@v4
        with:
          name: dist
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        if: env.SHOULD_PUBLISH_IMAGE == 'true'
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Log in to GitHub container registry
        if: env.SHOULD_PUBLISH_IMAGE == 'true'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push container image to registries
        if: env.SHOULD_PUBLISH_IMAGE == 'true'
        uses: docker/build-push-action@v5
        with:
          push: 'true'
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          context: .
          file: ./Dockerfile
